
local model = glueCreateModel()
glueSetGltfModel(model,ASPHALT)
glueSetPos(model,0.0,0.0,0.0)
glueSetScale(model,142.0,5.0,140.0)
glueSetRotate(model,0.0,0.0,0.0)
glueSetColider(model,false)

local model2 = glueCreateModel()
glueSetGltfModel(model2,LEATHER)
glueSetPos(model2,-230.0,0.0,0.0)
glueSetScale(model2,50.0,10.0,50.0)
glueSetColider(model2,false)

local player = glueCreatePlayer()
glueSetGltfModel(player,gltfTEST)
glueSetScale(player,10.0,10.0,10.0)
glueSetColider(player,true)
glueSetColiderScale(player,1.0,1.0,0.3)
glueSetDefaultAnimationName(player,"Running")
glueBindCamera(player)
glueSetLuaPath(player,"LuaScripts/player.lua")

local pointLight = glueCreatePointLight()
glueSetLightColor(pointLight,1.0,1.0,1.0)
glueSetPos(pointLight,1.1,5.0,1.1)
glueBindObject(player,pointLight)

local pointLight2 = glueCreatePointLight()
glueSetLightColor(pointLight2,1.0,1.0,1.0)
glueSetPos(pointLight2,1.1,1.1,3.1)
glueBindObject(player,pointLight2)

local pointLight3 = glueCreatePointLight()
glueSetLightColor(pointLight3,1.0,1.0,1.0)
glueSetPos(pointLight3,-1.0,3.0,-1.0)
glueBindObject(player,pointLight3)

local directionalLight = glueCreateDirectionalLight()
glueSetLightColor(directionalLight,1.0,1.0,1.0)
glueSetLightDirection(directionalLight,-200.0,-200.0,-200.0)
glueBindObject(player,directionalLight)
glueSetPos(directionalLight,200,200,200)

print("AAA")